spring.application.name=api-example

#spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

security.jwt.secret=${SECURITY_JWT_SECRET: 123456789012345678901212345678901234567890121234567890123456789012}
security.jwt.expiration=${SECURITY_JWT_EXPIRATION_MILLIS: 86400000}

spring.datasource.url=jdbc:postgresql://localhost:5432/api_example
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${SENHA_POSTGRESQL:root}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true